### ISSUE TITLE
Crashed 

### ISSUE THREAD

**Issue by semiconductor-siliconcarbidecube** [Tfarcenim/ReplayModForge-1201#1]
Crash report: https://mclo.gs/5Bng1fd

It looks like some serious issue with GUI rendering caused the by mod. Also, in some hover text bubbles, text is missing.

**Comment by semiconductor-siliconcarbidecube** [comment]
> Crash report: https://mclo.gs/5Bng1fd
> 
> It looks like some serious issue with GUI rendering caused the by mod. Also, in some hover text bubbles, text is missing.

More on the this:

It looks like an issue with Rubidium just as mentioned on Curseforge page. Worked with no issue when I swapped Rubidium with Xenon that does the same job(https://modrinth.com/mod/xenon-forge).

**Comment by Tfarcenim** [comment]
Rubidium is known to cause problems with ReplayMod so it should be replaced with Embeddium or similar.  I would mark it as incompatible, but that would prevent Embeddium from working as well.

**Comment by semiconductor-siliconcarbidecube** [comment]
> Rubidium is known to cause problems with ReplayMod so it should be replaced with Embeddium or similar. I would mark it as incompatible, but that would prevent Embeddium from working as well.

Looks like replacing it won't work either. The hover bubbles are broken as well. The bubble is there but text is completely missing. It looks like an issue with the GUI. 

When an item from the creative inventory is clicked it opens the recordings window(Only in certain rows. In some occasions, the recording stops when clicked on a certain item from the menu). Sometimes, when survival menu is opened the game crashes.
